/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as DramaSlugRouteImport } from './routes/drama.$slug'
import { Route as WatchSlugEpisodeRouteImport } from './routes/watch.$slug.$episode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const DramaSlugRoute = DramaSlugRouteImport.update({
  id: '/drama/$slug',
  path: '/drama/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugEpisodeRoute = WatchSlugEpisodeRouteImport.update({
  id: '/watch/$slug/$episode',
  path: '/watch/$slug/$episode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/drama/$slug': typeof DramaSlugRoute
  '/watch/$slug/$episode': typeof WatchSlugEpisodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/drama/$slug': typeof DramaSlugRoute
  '/watch/$slug/$episode': typeof WatchSlugEpisodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/drama/$slug': typeof DramaSlugRoute
  '/watch/$slug/$episode': typeof WatchSlugEpisodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/browse' | '/drama/$slug' | '/watch/$slug/$episode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/browse' | '/drama/$slug' | '/watch/$slug/$episode'
  id: '__root__' | '/' | '/browse' | '/drama/$slug' | '/watch/$slug/$episode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  DramaSlugRoute: typeof DramaSlugRoute
  WatchSlugEpisodeRoute: typeof WatchSlugEpisodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drama/$slug': {
      id: '/drama/$slug'
      path: '/drama/$slug'
      fullPath: '/drama/$slug'
      preLoaderRoute: typeof DramaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug/$episode': {
      id: '/watch/$slug/$episode'
      path: '/watch/$slug/$episode'
      fullPath: '/watch/$slug/$episode'
      preLoaderRoute: typeof WatchSlugEpisodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  DramaSlugRoute: DramaSlugRoute,
  WatchSlugEpisodeRoute: WatchSlugEpisodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
